default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: nike12
  host: localhost

development:
  <<: *default
  database: to_do_development

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  database: to_do_production
  username: www
  password: <%= ENV['WWW_DATABASE_PASSWORD'] %>
